/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void reverseGreetingTest() {
        App classUnderTest = new App();
        assertEquals(".DDT ot emocleW !dlroW olleH", classUnderTest.getReverseGreeting(), "reverse greeting should be '.DDT ot emocleW !dlroW olleH'");
    }    
}
